"""Generate brand assets for the Samra desktop app + installer.

  1. app/brand.py  — the squircle app icon embedded as base64 (used by the UI app_mark,
     so the real icon shows everywhere with zero packaging/path fuss).
  2. installer/wiz_large.bmp (+@2x)  — Welcome/Finish left panel: dark brand panel.
  3. installer/wiz_small.bmp (+@2x)  — inner-page top-right badge: icon on white.

Run after _make_icon.py (which writes samra.png)."""
import base64
import io
import os
from PIL import Image, ImageDraw, ImageFont
import arabic_reshaper
from bidi.algorithm import get_display


def shape(text):
    """Reshape + bidi-order Arabic so PIL renders connected glyphs correctly."""
    return get_display(arabic_reshaper.reshape(text))

ICON_PNG = "samra.png"            # 512 squircle, produced by _make_icon.py
ACCENT = (0xEC, 0xA9, 0x3C)
ACCENT_DEEP = (0xC9, 0x88, 0x1F)
BG = (0x0E, 0x0F, 0x12)
SURFACE = (0x15, 0x17, 0x1D)
TEXT = (0xF3, 0xF1, 0xEC)
TEXT2 = (0x9B, 0xA1, 0xAC)

os.makedirs("installer", exist_ok=True)
icon = Image.open(ICON_PNG).convert("RGBA")


# ---- 1. embed icon as base64 -> app/brand.py --------------------------------
def b64_of(img, size):
    buf = io.BytesIO()
    img.resize((size, size), Image.LANCZOS).save(buf, format="PNG")
    return base64.b64encode(buf.getvalue()).decode("ascii")

icon_b64 = b64_of(icon, 256)
with open("app/brand.py", "w", encoding="utf-8") as f:
    f.write('"""Samra brand assets embedded for the UI (auto-generated by _make_brand.py)."""\n\n')
    f.write('APP_ICON_B64 = "%s"\n' % icon_b64)
print("wrote app/brand.py (icon base64, %d chars)" % len(icon_b64))


# ---- font helper ------------------------------------------------------------
def font(size, bold=True):
    for name in (["seguibl.ttf", "segoeuib.ttf"] if bold else ["segoeui.ttf"]):
        try:
            return ImageFont.truetype("C:/Windows/Fonts/" + name, size)
        except Exception:
            continue
    return ImageFont.load_default()


def font_ar(size):
    # Arabic-capable faces (Segoe UI Black has no Arabic; these do).
    for name in ["segoeuib.ttf", "arialbd.ttf", "trbdfont.ttf", "arial.ttf"]:
        try:
            return ImageFont.truetype("C:/Windows/Fonts/" + name, size)
        except Exception:
            continue
    return ImageFont.load_default()


def vgrad(w, h, top, bot):
    g = Image.new("RGB", (w, h))
    px = g.load()
    for y in range(h):
        f = y / max(1, h - 1)
        px[0, y] = tuple(int(top[i] + (bot[i] - top[i]) * f) for i in range(3))
    for y in range(h):
        c = px[0, y]
        for x in range(w):
            px[x, y] = c
    return g


# ---- 2. large welcome panel (164x314 @1x, 328x628 @2x) ----------------------
def make_large(scale):
    w, h = 164 * scale, 314 * scale
    img = vgrad(w, h, BG, SURFACE).convert("RGBA")
    d = ImageDraw.Draw(img)
    # subtle amber glow band behind the icon
    ic = max(72 * scale, 1)
    icon_r = icon.resize((ic, ic), Image.LANCZOS)
    ix = (w - ic) // 2
    iy = int(h * 0.20)
    img.alpha_composite(icon_r, (ix, iy))
    # wordmark
    fa = font(34 * scale, bold=True)
    fb = font_ar(18 * scale)
    ft_ = font(12 * scale, bold=False)
    def center_text(text, y, fnt, fill):
        bb = d.textbbox((0, 0), text, font=fnt)
        tw = bb[2] - bb[0]
        d.text(((w - tw) // 2, y), text, font=fnt, fill=fill)
    center_text("SAMRA", iy + ic + 22 * scale, fa, TEXT)
    center_text(shape("سمره"), iy + ic + 22 * scale + 46 * scale, fb, ACCENT)
    # bottom tagline
    tag = "Audiobook downloader"
    bb = d.textbbox((0, 0), tag, font=ft_)
    d.text(((w - (bb[2] - bb[0])) // 2, h - 40 * scale), tag, font=ft_, fill=TEXT2)
    return img.convert("RGB")

make_large(1).save("installer/wiz_large.bmp")
make_large(2).save("installer/wiz_large_2x.bmp")
print("wrote installer/wiz_large.bmp (+@2x)")


# ---- 3. small badge (55x55 @1x, 110x110 @2x, 138 for hi-dpi) ----------------
def make_small(px):
    img = Image.new("RGB", (px, px), (255, 255, 255))
    pad = max(2, px // 12)
    ic = px - pad * 2
    img.paste(icon.resize((ic, ic), Image.LANCZOS), (pad, pad), icon.resize((ic, ic), Image.LANCZOS))
    return img

make_small(55).save("installer/wiz_small.bmp")
make_small(110).save("installer/wiz_small_2x.bmp")
make_small(138).save("installer/wiz_small_3x.bmp")
print("wrote installer/wiz_small.bmp (+@2x,@3x)")
